### ISSUE TITLE
项目默认启动不起来

### ISSUE THREAD

**Issue by hwtl** [Patrickleeee/springboot-activiti#1]
项目down下来启动不起来
追加了一个配置正常了
`<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>4.2.0.Final</version>
		</dependency>
`
但是访问就弹窗，这个账户密码不知道是什么呢
![image](https://user-images.githubusercontent.com/2331062/29316227-b6a27860-81f9-11e7-9310-7356fc918bfb.png)

**Comment by Patrickleeee** [comment]
用户名和密码,，需要在本地数据库中的自己添加一个

**Comment by Patrickleeee** [comment]
![image](https://user-images.githubusercontent.com/22017582/40965389-2148beea-68e0-11e8-8ecd-df3650a290d6.png)
