### ISSUE TITLE
demo需要密码

### ISSUE THREAD

**Issue by xiabasten** [Patrickleeee/springboot-activiti#2]
我按照示例  需要密码？请问多少啊

**Comment by Patrickleeee** [comment]
用户名和密码,，需要在本地数据库中的用户表自己添加一个就好了

**Comment by Patrickleeee** [comment]
![image](https://user-images.githubusercontent.com/22017582/40965090-6fc3b6fc-68df-11e8-9f16-262452fcd1db.png)
